name: Refresh Predictions

on:
  schedule:
    - cron: "0 */3 * * *"   # toutes les 3 h (UTC)
  workflow_dispatch:

jobs:
  call-refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Compute Paris date (YYYY-MM-DD)
        id: dateparis
        run: |
          PARIS_DATE=$(TZ="Europe/Paris" date +%F)
          echo "date=$PARIS_DATE" >> $GITHUB_OUTPUT
          echo "Paris date = $PARIS_DATE"

      - name: Build payload.json
        id: payload
        run: |
          cat > payload.json <<EOF
          {
            "date": "${{ steps.dateparis.outputs.date }}",
            "league_id": "L1",
            "matches": [
              {
                "home": "PSG",
                "away": "OM",
                "status": "scheduled",
                "odds": { "home": 1.70, "draw": 3.90, "away": 5.00, "over25": 1.85, "under25": 1.95 },
                "version": "baseline-v1"
              },
              {
                "home": "Lyon",
                "away": "Monaco",
                "status": "scheduled",
                "odds": { "home": 2.60, "draw": 3.40, "away": 2.60, "over25": 1.75, "under25": 2.05 },
                "version": "baseline-v1"
              },
              {
                "home": "Lille",
                "away": "Rennes",
                "status": "scheduled",
                "odds": { "home": 2.20, "draw": 3.30, "away": 3.20, "over25": 1.95, "under25": 1.85 },
                "version": "baseline-v1"
              }
            ]
          }
          EOF
          echo "file=payload.json" >> $GITHUB_OUTPUT
          echo "Built payload:"
          cat payload.json

      - name: Warm up API (/health) with retries
        env:
          API_BASE: https://ia-sport.onrender.com
        run: |
          set -euo pipefail
          for i in 1 2 3 4 5; do
            echo "Ping /health (attempt $i)..."
            code=$(curl -sS -o /dev/null -w "%{http_code}" "$API_BASE/health" || true)
            echo "HTTP $code"
            if [ "$code" = "200" ]; then
              echo "API is warm."
              exit 0
            fi
            sleep $((i*5))
          done
          echo "API did not warm up in time"; exit 1

      - name: Call /admin/refresh with retries
        env:
          API_BASE: https://ia-sport.onrender.com
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${ADMIN_TOKEN:-}" ]; then
            echo "Missing ADMIN_TOKEN secret"; exit 1
          fi

          for i in 1 2 3 4 5; do
            echo "POST /admin/refresh (attempt $i)..."
            http_code=$(curl -sS -o response.json -w "%{http_code}" \
              -X POST "$API_BASE/admin/refresh" \
              -H "Content-Type: application/json" \
              -H "X-Admin-Token: $ADMIN_TOKEN" \
              --data-binary "@${{ steps.payload.outputs.file }}" || true)

            echo "HTTP $http_code"
            cat response.json || true

            if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
              echo "Success."
              exit 0
            fi
            sleep $((i*8))
          done

          echo "Refresh failed after retries."
          exit 1
